# Generated by Django 2.2.7 on 2019-11-26 05:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('CPF', models.CharField(blank=True, max_length=14, null=True)),
                ('gender', models.CharField(blank=True, max_length=11, null=True)),
                ('role', models.CharField(blank=True, max_length=45, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('id_departament', models.IntegerField(blank=True, null=True)),
                ('id_supervisor', models.IntegerField(blank=True, null=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
